import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type AgentDocument = Agent & Document;

@Schema({ timestamps: true })
export class Agent {
  @Prop({ type: Types.ObjectId, ref: 'User' })
  userId: Types.ObjectId;

  @Prop({ unique: true })
  license?: string; // Generated by admin

  @Prop({ required: true })
  commissionRate: number;

  @Prop({ default: 0 })
  balance: number;

  @Prop()
  bio?: string;

  @Prop()
  phone?: string;

  @Prop({ type: [String] })
  documents?: string[]; // ID card, passport images

  @Prop({ enum: ['pending', 'approved', 'rejected'], default: 'pending' })
  status: string;
}

export const AgentSchema = SchemaFactory.createForClass(Agent);